const express = require('express');

const server = express();

const { PORT = 4000 } = process.env;

const shops = [
  {
    id: 1,
    title: 'Food shop',
    shopId: 1,
  },
  {
    id: 2,
    title: 'Appliances shop',
    shopId: 2,
  },
  {
    id: 3,
    title: 'Tableware shop',
    shopId: 3,
  },
  {
    id: 4,
    title: 'Furniture shop',
    shopId: 4,
  },
  {
    id: 5,
    title: 'Automobiles shop',
    shopId: 5,
  },
];

const products = [
  {
    id: 1,
    imgUrl: '',
    title: 'Berries',
    descr: 'Product description 1.1',
    category: '1',
    price: 10,
    shopId: 1,
  },
  {
    id: 2,
    imgUrl: '',
    title: 'Coffee',
    descr: 'Product description 1.2',
    category: '5',
    price: 20,
    shopId: 1,
  },
  {
    id: 3,
    imgUrl: '',
    title: 'Olive oil',
    descr: 'Product description 1.3',
    category: '2',
    price: 30,
    shopId: 1,
  },
  {
    id: 4,
    imgUrl: '',
    title: 'Almonds',
    descr: 'Product description 1.4',
    category: '3',
    price: 40,
    shopId: 1,
  },
  {
    id: 5,
    imgUrl: '',
    title: 'Salmon',
    descr: 'Product description 1.5',
    category: '4',
    price: 50,
    shopId: 1,
  },
  {
    id: 6,
    imgUrl: '',
    title: 'Tea',
    descr: 'Product description 1.6',
    category: '1',
    price: 60,
    shopId: 1,
  },
  {
    id: 7,
    imgUrl: '',
    title: 'Vacuum cleaner',
    descr: 'Product description 2.2',
    category: '5',
    price: 70,
    shopId: 2,
  },
  {
    id: 8,
    imgUrl: '',
    title: 'Food mixer',
    descr: 'Product description 2.3',
    category: '2',
    price: 80,
    shopId: 2,
  },
  {
    id: 9,
    imgUrl: '',
    title: 'Ironing',
    descr: 'Product description 2.4',
    category: '3',
    price: 90,
    shopId: 2,
  },
  {
    id: 10,
    imgUrl: '',
    title: 'Bread machine',
    descr: 'Product description 2.5',
    category: '4',
    price: 100,
    shopId: 2,
  },
  {
    id: 11,
    imgUrl: '',
    title: 'Mugs',
    descr: 'Product description 3.1',
    category: '1',
    price: 110,
    shopId: 3,
  },
  {
    id: 12,
    imgUrl: '',
    title: 'Dishs',
    descr: 'Product description 3.2',
    category: '5',
    price: 120,
    shopId: 3,
  },
  {
    id: 13,
    imgUrl: '',
    title: 'Cutlery',
    descr: 'Product description 3.3',
    category: '2',
    price: 130,
    shopId: 3,
  },
  {
    id: 14,
    imgUrl: '',
    title: 'Brew kettle',
    descr: 'Product description 3.4',
    category: '3',
    price: 140,
    shopId: 3,
  },
  {
    id: 15,
    imgUrl: '',
    title: 'Bowl',
    descr: 'Product description 3.5',
    category: '4',
    price: 150,
    shopId: 3,
  },
  {
    id: 16,
    imgUrl: '',
    title: 'Couch',
    descr: 'Product description 4.1',
    category: '1',
    price: 160,
    shopId: 4,
  },
  {
    id: 17,
    imgUrl: '',
    title: 'Chair',
    descr: 'Product description 4.2',
    category: '5',
    price: 170,
    shopId: 4,
  },
  {
    id: 18,
    imgUrl: '',
    title: 'Sofa',
    descr: 'Product description 4.3',
    category: '2',
    price: 180,
    shopId: 4,
  },
  {
    id: 19,
    imgUrl: '',
    title: 'Crib',
    descr: 'Product description 4.4',
    category: '3',
    price: 190,
    shopId: 4,
  },
  {
    id: 20,
    imgUrl: '',
    title: 'Home office',
    descr: 'Product description 4.5',
    category: '4',
    price: 200,
    shopId: 4,
  },
  {
    id: 21,
    imgUrl: '',
    title: 'Mercedes Benz',
    descr: 'Product description 5.1',
    category: '1',
    price: 210,
    shopId: 5,
  },
  {
    id: 22,
    imgUrl: '',
    title: 'Mustang',
    descr: 'Product description 5.2',
    category: '5',
    price: 220,
    shopId: 5,
  },
  {
    id: 23,
    imgUrl: '',
    title: 'Sportcar',
    descr: 'Product description 5.3',
    category: '2',
    price: 230,
    shopId: 5,
  },
  {
    id: 24,
    imgUrl: '',
    title: 'Dreamcar',
    descr: 'Product description 5.4',
    category: '3',
    price: 240,
    shopId: 5,
  },
  {
    id: 25,
    imgUrl: '',
    title: 'Tuktuk',
    descr: 'Product description 5.5',
    category: '4',
    price: 250,
    shopId: 5,
  },
];

server.get('/shops', (request, response) => {
  response.data = shops;
});

server.get('/products', (request, response) => {
  response.data = products;
});

server.listen(PORT, () => {
  console.log(`Server running. Use our API on port: ${PORT}`);
});
